name: lint

on:
  push:
    branches-ignore:
      - renovate/**
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - uses: Trim21/setup-poetry@dist/v1
      - uses: Trim21/install-poetry-project@dist/v1
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: precommit-2-${{ env.PY }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: precommit-2-${{ env.PY }}-

      - name: pre-commit
        run: pre-commit run --all-files --show-diff-on-failure && pre-commit gc
